### ISSUE TITLE
basic usage fails with SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by paulvi** [Instadapp/dsa-connect#48]
code below with basic usage just fails

```
require('dotenv').config() //https://github.com/motdotla/dotenv

const ETH_NODE_URL = process.env.ETH_NODE_URL;
const PRIVATE_KEY = process.env.PRIVATE_KEY;

// in nodejs
const Web3 = require('web3')
const DSA = require('dsa-connect');
const web3 = new Web3(new Web3.providers.HttpProvider(ETH_NODE_URL))

// in nodejs
const dsa = new DSA({
    web3: web3,
    mode: "node",
    privateKey: PRIVATE_KEY
});
```

```
/usr/local/bin/node /Users/paul/Workspaces/Ethereum/Instadapp/instadapp-get-started/usage.js
/Users/paul/Workspaces/Ethereum/Instadapp/instadapp-get-started/node_modules/dsa-connect/dist/index.js:11466
export default DSA;
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/paul/Workspaces/Ethereum/Instadapp/instadapp-get-started/usage.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

Process finished with exit code 1
```
See #47 and https://github.com/Instadapp/dsa-connect/pull/41#issuecomment-823240843

**Comment by DakshMiglani** [comment]
Seems like a bundler issue. confirming happens with version 0.1.9 only.
